### ISSUE TITLE
Identify and remove lower quality illustrations

### ISSUE THREAD

**Issue by whmii** [thoughtbot/foundry-fellowly#6]
Some of Fellowly is of a lower quality than others.

Illustrations need to be identified as either good, bad and need to be removed, or bad but the topic is important enough that it should be redesigned/updated.

Some outside opinions would be great.

**Comment by whmii** [comment]
Here is a dir of all the illus call them out by name if they suck haha
https://github.com/thoughtbot/foundry-fellowly/tree/master/lib

**Comment by whmii** [comment]
Had a good chat with @tabfugnic 

Here are some of the ones n the chopping block

**Comment by kaishin** [comment]
The lady with the fan, what happened to her legs?
I'd probably remove the bleeding heart.

**Comment by whmii** [comment]
- Asprin Box
- Single foot
- Sugar packet
- Towels
- Gym
- Running through exit
- Sandwich with 2 hands
- Ambulance
- Medikit
- Pellow


Other Notes:
- Tooth: remove tube
- dedupe dress shirts
- Remove table from intercom

**Comment by whmii** [comment]
![screencapture-thoughtbot-github-io-foundry-1434724580386](https://cloud.githubusercontent.com/assets/2489247/8255888/29f34868-1671-11e5-9c5f-f24c86d7e510.png)

**Comment by whmii** [comment]
Done
